language: android
jdk: oraclejdk8
sudo: false
android:
  components:
  - tools
  - tools
  - build-tools-27.0.3
  - android-27
cache:
  directories:
  - "$HOME/.gradle/caches/"
script:
- "./gradlew build jacocoTestReport publishSnapshot"
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: "./gradlew bintrayUpload"
  on:
    tags: true
